### PR TITLE
fix circle

### PR DESCRIPTION
**Pull request by hroskes**
wait until the tests pass, but I think they will

### CODE REVIEW

**Comment by usarica** [comment]
Can we set linkMELA=Yes from now on? I think this was the idea.

**Comment by hroskes** [comment]
ok, that's fine.  the tests are still failing though.

**Comment by hroskes** [comment]
Are you sure we want to print the whole MCFM header every time?  Maybe just if we call an MCFM process (right now only if Process=66)?

**Comment by usarica** [comment]
Since it is not complete now, maybe I can fix this later.

**Pull request merged**
